
services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - node_db
  
  migration:
    container_name: node_migration
    build: .
    environment:
      - POSTGRES_DB=student_db
      - POSTGRES_USER=akshat
      - POSTGRES_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    entrypoint: ["/app/migrate.sh"]
      
  node_db:
    container_name: node_db
    image: postgres:15.7-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - node_db_data:/var/lib/postgresql/data
 
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8888:80"
      env_file:
        - .env
      volumes:
        - pgadmin-data:/var/lib/pgadmin


volumes:
  node_db_data: {}
  pgadmin-data: {}
