apiVersion: v2
name: vault-setup
description: Vault installation and configuration
version: 0.1.0
dependencies:
  - name: vault
    version: "0.28.1"
    repository: "https://helm.releases.hashicorp.com"