global:
  namespace: vault
  
injector:
  nodeSelector:
    type: dependent_services
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "dependent_services" 
      effect: "NoSchedule"
server:
  nodeSelector:
    type: dependent_services
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "dependent_services"
      effect: "NoSchedule"
  standalone:
    enabled: true
  
ui:
  enabled: true