{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.clientMaxBodySize | default "5m" | quote}}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    - host: {{ .Values.ingress.appHost }}
      http:
        paths:
          {{- if .Values.api.enabled }}
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-api
            path: /
            pathType: Prefix
          {{- end}}
{{- end }}