{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.vault_setup.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault_setup.server | quote }}
      path: {{ .Values.vault_setup.path | default "kv" }}
      version: {{ .Values.vault_setup.version | default "v2" }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault_setup.auth.tokenSecretRef.name }}
          key: {{ .Values.vault_setup.auth.tokenSecretRef.key }}
{{- end }}