apiVersion: v2
name: prometheus-setup
description: Prometheus installation and configuration
version: 0.1.0
dependencies:
  - name: prometheus
    version: "0.50.2"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "0.50.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled