apiVersion: v2
name: monitoring
description: A Helm chart for loki, prometheus, grafana, promtail, blackbox exporter
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "65.7.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled

  - name: loki-stack
    version: "*"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled

  - name: prometheus-blackbox-exporter
    version: "9.0.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: blackbox-exporter.enabled