apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  auth-config.sh: |
    #!/bin/sh
    # Enable kubernetes auth method
    vault auth enable kubernetes
    
    # Configure kubernetes auth
    vault write auth/kubernetes/config \
      kubernetes_host="https://kubernetes.default.svc.cluster.local" \
      token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
      kubernetes_ca_cert="$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)" \
      issuer="https://kubernetes.default.svc.cluster.local"

    # Create policies
    vault policy write app-policy /vault/config-map/app-policy.hcl
    vault policy write admin-policy /vault/config-map/admin-policy.hcl
    
    # Create kubernetes auth roles
    vault write auth/kubernetes/role/my-application \
      bound_service_account_names=my-application \
      bound_service_account_namespaces=default \
      policies=app-policy \
      ttl=1h

    # Enable KV secrets engine if not already enabled
    vault secrets enable -path=secret -version=2 kv

    # Create initial secrets (optional)
    vault kv put secret/my-application/credentials \
      username="initial-user" \
      password="initial-password"