apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policies
data:
  app-policy.hcl: |
    # Allow applications to read secrets from their specific paths
    path "secret/data/${identity.entity.aliases.auth_kubernetes_*.metadata.service_account_namespace}/${identity.entity.aliases.auth_kubernetes_*.metadata.service_account_name}/*" {
      capabilities = ["read"]
    }
    
    # Allow applications to read their own metadata
    path "auth/token/lookup-self" {
      capabilities = ["read"]
    }

  admin-policy.hcl: |
    # Allow managing secrets
    path "secret/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    
    # Allow managing auth methods
    path "auth/*" {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }
    
    # Allow managing policies
    path "sys/policies/acl/*" {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }